language: perl
sudo: false
env:
   global:
   - AUTOMATED_TESTING="1"
   # Test::DependentModules
   - PERL_TEST_DM_CPAN_VERBOSE=1
   - PERL_TEST_DM_PROCESSES=4
addons:
   apt:
      packages:
      - aspell
      - aspell-en
perl:
   - "5.22"
   - "5.20"
   - "5.18"
   - "5.16"
   - "5.14"
   - "5.12"
   - "5.10"
before_install:
   - export AUTOMATED_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
   - git config --global user.name "TravisCI"
   - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
install:
   - "cpanm --quiet --notest Dist::Zilla"
   - "dzil authordeps | cpanm --quiet --notest"
   - "dzil listdeps --develop  | cpanm --quiet --notest"
script:
   # Author testing in hope that this will trigger Test::Spelling tests in
   # dependent modules
   - export AUTHOR_TESTING=1
   - dzil smoke --release --author
